version: '3'

services:
  composer:
    image: composer:latest
    volumes:
      - ./:/app
    working_dir: /app

  php:
    image: php:7.4-cli-alpine
    volumes:
      - ./:/app
    working_dir: /app

  webserver:
    image: matthiasnoback/php-for-the-web-webserver
    build: docker/webserver/
    volumes:
      - ./:/app
    ports:
      - "8000:8000"

  challenge_chapter_04:
    image: matthiasnoback/php-for-the-web-webserver
    volumes:
      - ./:/app
    ports:
      - "8001:8000"
    command: challenge_chapter_04/public/

  challenge_chapter_07:
    image: matthiasnoback/php-for-the-web-webserver
    volumes:
      - ./:/app
    ports:
      - "8002:8000"
    command: challenge_chapter_07/public/

  challenge_chapter_08:
    image: matthiasnoback/php-for-the-web-webserver
    volumes:
      - ./:/app
    ports:
      - "8003:8000"
    command: challenge_chapter_08/public/

  challenge_chapter_09:
    image: matthiasnoback/php-for-the-web-webserver
    volumes:
      - ./:/app
    ports:
      - "8004:8000"
    command: challenge_chapter_09/public/
